
logging:
  config: classpath:logback-${spring.profiles.active}.yml

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      allow-pool-suspension: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQ5InnoDBDialect
    database-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
  mybatis:
    configuration:
      map-underscore-to-camel-case: true

---
spring:
  profiles: dev
  datasource:
    hikari:
      driver-class-name=net: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
  thymeleaf:
    cache: false
  resource:
    cache:
      period: 0



#  mybatis.configuration.map-underscore-to-camel-case=
